== HTMX Patterns

* Typical patterns/use cases for web applications

=== Progressive Enhancement

[source,html]
----
<html>
...
<body hx-boost="true">
...
</body>
</html>
----

=== Progressive Enhancement

[source,html,highlight="1,2,6..10"]
----
<form id="new-todo-form" th:action="@{/}" 
    method="post" th:object="${item}">
    <input id="new-todo-input" class="new-todo"
        autocomplete="false"
        name="title"
        th:field="*{title}"
        hx-target="#todo-list"
        hx-swap="beforeend"
        hx-post="/"
        hx-trigger="keyup[key=='Enter']"
    >
</form>
----

* Keep the normal form, such that it even works without Javascript

=== Sorting

[source,html,highlight="2,3|4|5"]
----
<th>
<div hx-get="/manager/users?sort=username,desc
&size=10&page=0&query=" 
hx-target="#users-table-wrapper" 
hx-push-url="true">
</th>
----

[.notes]
--
* Was haben wir hier vergessen?
* Das geht nur mit aktivierten JS
* anchor verwenden 
--

=== Paging

[source,html,highlight="2,4|5,6"]
----
<a hx-get="/manager/users?sort=username,ASC
&size=10&page=0&query=" 
hx-target="#users-table-wrapper" 
hx-push-url="true">1</a>
<a hx-get="/manager/users?sort=username,ASC
&size=10&page=1&query=" 
hx-target="#users-table-wrapper" 
hx-push-url="true">2</a>
...
----

[.notes]
--
* Hier fehlt was?
* href verwenden
--

=== Inline Updates

[source,html,highlight="3|4,6"]
----
<a href="/manager/users/57/change-status" 
title="Benutzerstatus ändern" 
hx-get="/manager/users/57/change-status" 
hx-target="closest td" 
hx-swap="outerHTML">deaktiviert</a>
----

[.notes]
--
* Hier sieht man gut progressive enhancement
* hx requets -> nur die Zeile erzeugen
* normaler href -> die ganze Seite wieder als redirect (nicht optimal weil hier ggf. sort etc verloren geht)
--

=== Inline Updates Server Side

[source,java,highlight="2,3|11"]
----
@GetMapping(value = "/manager/users/{id}/change-status", 
            produces = "text/html-partial", 
            headers = "HX-Request")
public String changeStatus_htmx(@PathVariable Long id, 
    Pageable pageable, String query, Model model) {
    User user = userManagementService.findOneById(id);
    userManagementService.changeStatus(user);
    createUsersPageModel(model, pageable, Optional.ofNullable(query));
    model.addAttribute("user", user);

    return "usermanagement/fragments/user-row-contents :: user-status";
}
----

=== Trigger Client side Events

[source,html, highlight="6|4"]
----
<span th:fragment="active-items-count"
      id="active-items-count"
      class="todo-count"
      hx-get="/active-items-count"
      hx-swap="outerHTML"
      hx-trigger="itemAdded from:body">
...
</span>
----

=== Trigger Client side Events Server Side

[source,java, highlight="7,8"]
----
@PostMapping(headers = "HX-Request")
public String htmxAddTodoItem(TodoItemFormData formData, 
    Model model, HttpServletResponse response) {
    TodoItem item = repository.save(...);
    model.addAttribute("item", toDto(item));

    response.setHeader("HX-Trigger", "itemAdded");
    return "fragments :: todoItem";
}
----

=== Endless scrolling

[source,java,highlight="6,15"]
----
@GetMapping
public String index(Model model, Pageable pageable) {
    Slice<Location> slice = repository.findAll(pageable);
    model.addAttribute("slice", slice);
    model.addAttribute("items", slice.getContent());
    return "endless-scrolling/index";
}

@GetMapping
@HxRequest
public String items(Model model, Pageable pageable) {
    Slice<Location> slice = repository.findAll(pageable);
    model.addAttribute("slice", slice);
    model.addAttribute("items", slice.getContent());
    return "endless-scrolling/table :: list";
}
----

=== Endless scrolling 2

[source,html,highlight="3|7,8,9"]
----
<th:block th:each="item, iStat : ${items}">
    <th:block th:if="${!iStat.last}">
        <li th:text="${item.name}"></li>
    </th:block>
    <th:block th:if="${iStat.last}">
        <li
            hx:get="@{/endless-scrolling?sort={sort}&page={page}&size={size}(page=${slice.getNumber + 1},size=5,sort='name,desc')}"
            hx-trigger="intersect once"
            hx-swap="afterend"
            th:text="${item.name}"
        ></li>
    </th:block>
</th:block>
----

=== Much more

* Modal dialogs
* Inline editing/validation
* Active search
* lazy loading
* Websockets, Server Send Events
* ...



